name: rainbench
description: Flutter benchmark for reactive libraries
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    bloc: ^8.1.2
    context_watch: ^1.0.2
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.3
    flutter_localizations:
        sdk: flutter
    flutter_mobx: ^2.2.0+1
    flutter_solidart: ^1.7.0
    intl: ^0.18.0
    mobx: ^2.2.3
    signals: ^2.1.10
    state_beacon: ^0.14.5
    statsfl: ^2.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^1.0.0
    very_good_analysis: ^5.1.0

flutter:
    uses-material-design: true
    generate: true
