name: rainbench
description: Flutter benchmark for reactive libraries
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    context_watch: ^1.0.2
    flutter:
        sdk: flutter
    flutter_mobx: ^2.2.0+1
    flutter_solidart: ^1.7.0
    mobx: ^2.3.0
    signals: ^2.1.10
    state_beacon: ^0.24.0

dev_dependencies:
    very_good_analysis: ^5.1.0

flutter:
    uses-material-design: true
